import type { Metadata } from "next";
import { Overpass} from "next/font/google";
import "../styles/globals.css";
import "../styles/icons.css"
import "../styles/custom.css"
import { ToastProvider } from "@/components/ui/toast-message";

const overpass = Overpass({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${overpass.className} antialiased`}
      >
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
